### ISSUE TITLE
[Question] Flatlaf properties file location

### ISSUE THREAD

**Issue by hhslepicka** [DJ-Raven/swing-toast-notifications#1]
First of all, thank you for this very nice package! 
I am exploring it, and I would like to understand better where the Flatlaf properties file should be placed for the configuration to take effect.

I tried to add it to the `resources` folder of my project, but I guess I am missing some configuration on the code side.

**Comment by DJ-Raven** [comment]
If you using maven project the properties file should be in resources folder for example `src/main/resources/style/FlatLaf.properties`

``` java
FlatLaf.registerCustomDefaultsSource( "style" );
```
You can check here https://www.formdev.com/flatlaf/how-to-customize/
