### ISSUE TITLE
Force show it in light or dark mode

### ISSUE THREAD

**Issue by cedrosfreeshop** [DJ-Raven/swing-toast-notifications#10]
Is there a proprieties or method to force show it in light/dark mode and not according to the flat theme

**Comment by DJ-Raven** [comment]
You can use properties `Toast.background` and `Toast.foreground`

Example add this properties to your FlatLaf.properties
```
Toast.background=#505050
Toast.foreground=#f5f5f5
```

Or only for `info`

```
Toast.info.background=#505050
Toast.info.foreground=#f5f5f5
```

And update jar library to [`v1.0.4`](https://github.com/DJ-Raven/swing-toast-notifications/tree/main/library)
