### ISSUE TITLE
Hi Raven, I have trouble when i install this library to my project in netbean with maven

### ISSUE THREAD

**Issue by ilbdculuv** [DJ-Raven/swing-toast-notifications#9]
![image_2024-11-02_235902951](https://github.com/user-attachments/assets/d1ee1647-e565-4e73-b873-6ad15ad6738e)

**Comment by ilbdculuv** [comment]
Can you help me to fix it? Thanks!

**Comment by DJ-Raven** [comment]
In netbean here step to install.
1. Right click on the project `Dependencies` then click `Add Dependency...`
2. Fill the `Group ID` `Artifact ID` and `Version` the n click `Add`

![2024-11-03_003321](https://github.com/user-attachments/assets/d1170435-9927-4b74-9c65-8a3313f2cd6d)

3. Right click on the `swing-toast-notifications-1.0.3.jar` and click `Manually install artifact`

![2024-11-03_003347](https://github.com/user-attachments/assets/6b857683-0f9b-44f8-b2df-51b5125a92b3)

4. Browse to jar library then click `Install locally`

![2024-11-03_003412](https://github.com/user-attachments/assets/6a3ec668-2ff8-4b56-903a-003f580ebe0a)

Done.
